image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - build
  - test

variables:
  project: "sst-sdk-dotnet"

before_script:
  - "cd src/"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test"