image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

variables:
  project: "sst-sdk-dotnet"

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

.test: &dotnet_test
  stage: test
  script:
    - "dotnet test"

test:sdk:5: 
  <<: *dotnet_test
  image: mcr.microsoft.com/dotnet/sdk:5.0

test:sdk:6:
  <<: *dotnet_test
  image: mcr.microsoft.com/dotnet/sdk:6.0