stages:
  - build
  - test
  - package

image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_NOLOGO: "true"

build:
  stage: build
  script:
    - "dotnet build"

.test: &dotnet_test
  stage: test
  script:
    - echo running "dotnet test --framework net$SDK_VERSION" 
    - "dotnet test --framework net$SDK_VERSION"

test:sdk:6:
  <<: *dotnet_test
  variables:
    SDK_VERSION: "6.0"

pack:
  stage: package
  script:
    - dotnet pack SymplifySDK
